### ISSUE TITLE
Import failure in Python 3

### ISSUE THREAD

**Issue by eerimoq** [johan-sports/pyheatshrink#16]
Hello!

Importing heatshrink (version 0.3.2) in Python 3 fails with the exception below. Seems the ``__builtin__`` module is not available in Python 3, but only Python 2.

Looks like the Python 3 support is experimental, and has not yet been released to PyPI. When do you plan on releasing it?

```
> python3
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import heatshrink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/heatshrink/__init__.py", line 2, in <module>
    from .streams import open, EncodedFile
  File "/usr/local/lib/python3.6/dist-packages/heatshrink/streams.py", line 5, in <module>
    from __builtin__ import open as builtin_open
ModuleNotFoundError: No module named '__builtin__'
>>> 
```

**Comment by eerimoq** [comment]
@dsnipe @kalouantonis When can it be released?

**Comment by eerimoq** [comment]
Any chance this can be fixed? If not I'll probably fork this repository and release it to PyPI under another name.

**Comment by dsnipe** [comment]
@eerimoq please, follow the discussion in #17
